### ISSUE TITLE
As user, I want to see recommendations for how to satisfy the security criteria

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/DevicePortal#14]
Per question and OS there should be a brief recommendation on how this point can be satisfied, possibly with links to external resources. We will need an html/markdown field to store this.

**Comment by muzzi11** [comment]
Misread this, currently recommendation is per question but not per OS. General recommendation might be desirable so will leave that in and add support for recommendations per OS type (version independent).

**Comment by muzzi11** [comment]
OS type field for SecurityRecommendations acts as a mask, in order to add a general recommendation you can set the value to something like 2147483647 (=2^31 - 1).
