### ISSUE TITLE
As institute manager, I want to see device details

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/DevicePortal#18]
Show all available info from CMDB when you click a device.

**Comment by JBonsink** [comment]
Is this issue blocked by missing connection with CMDB? Or do you want to show more data from the Excel sheet?

**Comment by goomens** [comment]
The data is the same so we can get it from the sheet, in particular the building, room and outlet , date last seen and cost centre.

**Comment by goomens** [comment]
The columns are there but all empty, I assume this will be fixed once we have #17 working :-)
