### ISSUE TITLE
As user, I want to see my devices

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/DevicePortal#2]
Provide the user of an overview of all UvA-registered devices, as registered in the UvA's CMDB (for now my a monthly Excel import) and the security status (Intune activated yes or now).

**Comment by goomens** [comment]
Given the cryptic values, I think the columns for in the device overview need column headers :-).

**Comment by JBonsink** [comment]
Column headers have been added.

**Comment by JBonsink** [comment]
Intune securtity status check hasn't been implemented yet.

**Comment by JBonsink** [comment]
If tablet and no OS defined in import. It's always Android if not Apple.
