### ISSUE TITLE
As user, I want to report errors in device data

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/DevicePortal#22]
If some info about a device is incorrect, there should be a way to indicate this, e.g.
- Device doesn't exist anymore
- Device doesn't belong to me
- Operating system has changed

Store these changes as a delta with respect to the CMDB data, so that they can be reported to ICTS and that in a new CMDB export we can see whether they have been processed.

**Comment by JBonsink** [comment]
Show changes in system as pending change. Dont wait till ICTS manually updates data.

**Comment by muzzi11** [comment]
Log all changes to devices, not just operating system changes. Different changes require different permissions, e.g. user should be able to flag a device as no longer belonging to them, but only a institute manager should be allowed to actually reassign the device.

Device doesn't exist anymore should be a new status (Lost).
