### ISSUE TITLE
As institute manager, I want to see a status overview per institute

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/DevicePortal#23]
In the institute tiles in https://secure.science.uva.nl/faculty, add more some info:
- Instead of just complete/incomplete, show four different statuses: Intune completed, portal check submitted, portal check authorized, none 
- Add a progress bar for devices as well (with the same statuses)

**Comment by goomens** [comment]
This looks good! One last thing: are the managed devices are still included in the device progress bar? If so, maybe give them a dark grey bar to make it clear that the security check doesn't apply to them.

**Comment by JBonsink** [comment]
Show managed devices in stats, including users with managed devices.

**Comment by goomens** [comment]
There are no users with managed devices yet!

**Comment by JBonsink** [comment]
* added UsersManagedDevices to department stats. A managed deviced is not Intune & user cant submit it in device portal.
