### ISSUE TITLE
As institute manager, I want to see labnet data

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/DevicePortal#32]
The Fortinet gateway has some additional information on certain machines that is useful to have. Import this information periodically into the portal. Fields:
- The labnet number/name (if any) a device is in (labnets have an owner as well which we are probably going to want to register as well at a later stage)
- Show the security category based on IP address: <128, 128-191, >191
- Operating system (type + version): use Intune if available, then labnet, then CMDB

Devices can be matched to Intune and CMDB on MAC address.

**Comment by JBonsink** [comment]
Add table for managing labnets include owner & location.
