### ISSUE TITLE
As institute manager, I want to edit device fields

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/DevicePortal#36]
Add in the #35 dialog the ability to edit fields (with history being saved):
- Building (maybe as a dropdown with the values in the mapping from #34)
- Room
- Outlet
- User

**Comment by goomens** [comment]
When running an update from the CMDB, we only overwrite user-edited fields if the value from the CMDB is different from the value that was set at the time the user edited the field.

**Comment by goomens** [comment]
After an edit if you view the history before refreshing the page, the edit shows as made my the CMDB importer! After refreshing I seem to have a duplicate history entry (in the database there is only one row):
![Screen Shot 2021-06-07 at 6 27 58 AM](https://user-images.githubusercontent.com/5849619/120959195-87d78f80-c759-11eb-9865-c6b39aea2e16.png)

**Comment by muzzi11** [comment]
Fixed the first one, not sure if that inadvertently fixed the second issue because I can't reproduce that locally.
