### ISSUE TITLE
As approver, I want to approve/reject filled out checks

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/DevicePortal#8]
For users with approver rights (as set up in #6), the portal should show an overview of open approval requests, allowing them to view the fields filled out and approve/reject the form.

**Comment by goomens** [comment]
Why do I only see my last name on https://secure.science.uva.nl/requests?

**Comment by muzzi11** [comment]
This was a bug in creating new users on first login. To fix this either manually adjust the name in the db or delete the user and login again (this would require deleting and re-adding devices so I'd recommend the first option).
